services:
  postgres:
    image: postgres:16-alpine
    container_name: shortener-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: url_shortener_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shortener-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: shortener-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  url-api:
    image: urlshortener-api
    container_name: shortener-api
    restart: always
    build:
      context: .
      dockerfile: src/Services/UrlShortener.API/Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=shortener-postgres;Database=url_shortener_db;Username=postgres;Password=postgres_pass
      - ConnectionStrings__Redis=shortener-redis:6379
      - RabbitMQOptions__Host=shortener-rabbitmq
      - RabbitMQOptions__UserName=guest
      - RabbitMQOptions__Password=guest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  url-analytics:
    image: urlshortener-analytics
    container_name: shortener-analytics
    restart: always
    build:
      context: . 
      dockerfile: src/Services/UrlShortener.Analytics/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=shortener-postgres;Database=url_shortener_db;Username=postgres;Password=postgres_pass
      - RabbitMQOptions__Host=shortener-rabbitmq
      - RabbitMQOptions__UserName=guest
      - RabbitMQOptions__Password=guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: