// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Persistence;

#nullable disable

namespace UrlShortener.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260624152943_AddIdColumnToTableLinkStats")]
    partial class AddIdColumnToTableLinkStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Persistence.Models.LinkStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("LinksStats");
                });

            modelBuilder.Entity("UrlShortener.Persistence.Models.ShortUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LongUrl")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("UrlShortener.Persistence.Models.LinkStats", b =>
                {
                    b.HasOne("UrlShortener.Persistence.Models.ShortUrl", "ShortUrl")
                        .WithOne()
                        .HasForeignKey("UrlShortener.Persistence.Models.LinkStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
